### ISSUE TITLE
改造后页面报404，看了prd目录下的文件不是原来的文件名了，请问需要改index.html么？

### ISSUE THREAD

**Issue by julyzz** [leeonfield/migrate-ykit-to-webpack-4#2]

**Comment by leeonfield** [comment]
是 yapi 吗？有更详细的描述吗？

**Comment by julyzz** [comment]
是yapi。npm run build-client后，在static/prd目录下新生成了很多文件，如main.257e79f3.bundle.js，manifest.a8a4f57e.bundle.js，npm.antd.ac9f2276.bundle.js等等，但原来ykit build出来在 prd目录下 是assets.js?v=0.7474560774215564 ，lib，lib2，lib3

**Comment by leeonfield** [comment]
404 是找不到入口 html 还是找不到前端路由？打开调试看下页面信息，更详细的描述信息指的是问题的描述

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by julyzz** [comment]
可以提供下改写后的index.html文件么？

**Comment by julyzz** [comment]
应该是前端的路由不对，升级前的index.html 如下：`<script>
    document.write('<script src="/prd/assets.js?v=' + Math.random() + '"><\/script>');
</script>

<script>
    document.write('<link rel="stylesheet"  href="/prd/' + window.WEBPACK_ASSETS['index.js'].css + '" />');
</script>
</head>
<body>
<div id="yapi" style="height: 100%;"></div>


<script>
    document.write('<script src="/prd/' + window.WEBPACK_ASSETS['manifest'].js + '"><\/script>');
</script>
<script>
    document.write('<script src="/prd/' + window.WEBPACK_ASSETS['lib3'].js + '"><\/script>');
</script>
<script>
    document.write('<script src="/prd/' + window.WEBPACK_ASSETS['lib2'].js + '"><\/script>');
</script>
<script>
    document.write('<script src="/prd/' + window.WEBPACK_ASSETS['lib'].js + '"><\/script>');
</script>

<script>
    document.write('<script src="/prd/' + window.WEBPACK_ASSETS['index.js'].js + '"><\/script>');
</script>`

升级后应为打包的文件名都变了，所以不能再使用原来的index.html了吧？请问如何改写呢，谢谢执教。

**Comment by leeonfield** [comment]
https://github.com/leeonfield/yapi/tree/feature/webpack-v4
我配置了一版，可以参考下

**Comment by julyzz** [comment]
大佬好，按照你的配置项目可以跑起来了，但在使用中如果遇到underscore的话会报：
`Uncaught TypeError: _underscore.default.find is not a function`
请问有遇到过不？

**Comment by leeonfield** [comment]
没遇到这个问题
btw，如上，这个可以描述清晰一点

**Comment by julyzz** [comment]
babel/cli里引用了lodash，两者冲突了，用lodash替换underscore解决了这个问题
