### ISSUE TITLE
升级后接口编辑页面出现underscore库和lodash库冲突问题

### ISSUE THREAD

**Issue by julyzz** [leeonfield/migrate-ykit-to-webpack-4#3]
错误日志为：TypeError: _underscore. default. isEqual is not a function
at SchemaObjectComponent. shouldComponent Update （SchemaJson.js：679）
…
不知大佬遇到过以上问题不？

**Comment by leeonfield** [comment]
https://github.com/leeonfield/migrate-ykit-to-webpack-4/issues/2#issuecomment-756599469

跟这个问题是一样的吗🤔

**Comment by julyzz** [comment]
嗯，是属于同一个问题。yapi使用了json-schema-editor-visual库，这个库又依赖了underscore库。所以目前lodash和underscore是共存的，不知道有什么方法可以将underscore或者lodash完全替换不，只使用两者中一个工具库

**Comment by leeonfield** [comment]
解决眼前的吧，批量改对你的成本比较大，除非你有二次开发的诉求

**Comment by julyzz** [comment]
像这种冲突有什么好办法么？
